// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUVF5BQK1XzXOTkhDNdgRs7YsMZ35M6A',
    appId: '1:655183490332:web:9b3235235b3bdd7290ded9',
    messagingSenderId: '655183490332',
    projectId: 'pmanager-285af',
    authDomain: 'pmanager-285af.firebaseapp.com',
    storageBucket: 'pmanager-285af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kNVaDkAeSqwNSTVhc9PJizUzwc50WdY',
    appId: '1:655183490332:android:97926aa9e06bba8090ded9',
    messagingSenderId: '655183490332',
    projectId: 'pmanager-285af',
    storageBucket: 'pmanager-285af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQx_pl2hPMqB2uADl7dQwUQ8qoPOmmoQ',
    appId: '1:655183490332:ios:5ff6cfcb5d2643cc90ded9',
    messagingSenderId: '655183490332',
    projectId: 'pmanager-285af',
    storageBucket: 'pmanager-285af.appspot.com',
    iosClientId: '655183490332-ktih28s8b5ei9obe6d0d6kh49sur9mqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQx_pl2hPMqB2uADl7dQwUQ8qoPOmmoQ',
    appId: '1:655183490332:ios:db978fa73bb0b2bb90ded9',
    messagingSenderId: '655183490332',
    projectId: 'pmanager-285af',
    storageBucket: 'pmanager-285af.appspot.com',
    iosClientId: '655183490332-srlrmbev9g0ghno4sohufsf1tldidk5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pmanager.RunnerTests',
  );
}
